# Generated by Django 4.2.4 on 2024-01-08 06:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0009_paymenttermsupdates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paryroll_employee',
            new_name='payroll_employee',
        ),
    ]
