# Generated by Django 4.2.4 on 2024-01-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0002_rename_paryroll_employee_payroll_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll_employee',
            name='user',
        ),
    ]
