# Generated by Django 4.2.4 on 2024-01-12 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0009_paymenttermsupdates'),
        ('Company_Staff', '0003_remove_payroll_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_group', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payroll_employee',
            name='IFSC',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll_employee',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll_employee',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payroll_employee',
            name='transaction_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255, null=True)),
                ('login_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails')),
            ],
        ),
    ]
