# Generated by Django 4.2.4 on 2024-01-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_bloodgroup_alter_payroll_employee_ifsc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.payroll_employee'),
        ),
    ]
