# Generated by Django 4.2.4 on 2024-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_comment_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll_employee',
            name='vsalary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
