# Generated by Django 4.2.4 on 2024-01-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0006_payroll_employee_vsalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll_employee',
            name='vsalary',
        ),
    ]
