# Generated by Django 4.2.4 on 2024-01-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_remove_payroll_employee_vsalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_employee',
            name='salary_type',
            field=models.CharField(default='Fixed', max_length=100, null=True),
        ),
    ]
