# Generated by Django 4.2.4 on 2024-01-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0008_alter_payroll_employee_salary_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_employee',
            name='Aadhar',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payroll_employee',
            name='acc_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
