# Generated by Django 4.2.4 on 2024-01-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0009_alter_payroll_employee_aadhar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_employee',
            name='salaryrange',
            field=models.CharField(choices=[('1-10', '1-10'), ('10-15', '10-15'), ('15-31', '15-31')], default='1-10', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payroll_employee',
            name='status',
            field=models.CharField(default='Active', max_length=200, null=True),
        ),
    ]
