# Generated by Django 4.2.4 on 2024-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0010_alter_payroll_employee_salaryrange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_employee',
            name='workhr',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
