# Generated by Django 4.2.4 on 2024-01-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0009_paymenttermsupdates'),
        ('Company_Staff', '0019_alter_payroll_employee_acc_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comment',
            new_name='payroll_employee_comment',
        ),
    ]
